config/routes.rb
Rails.application.routes.draw do
  resources :mangas do
    resources :chapters
  end
  resources :teams
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :products do
    collection do
      post :import
      post :remove_all_records
      get :get_price
      get :csv
    end
  end
  resources :departments
  resources :employees
  resources :comments
  root 'pages#home'
  get 'test' => 'pages#test'

  resources :records
  # root 'records#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :chapters

  def update_info
    manga_info = Nokogiri::HTML(open(url))
    cover = manga_info.css('.thumbnail img').first.attr('src')
    title = manga_info.xpath("//div[@class='large comic']/h1/text()").to_s.squish
    description = manga_info.xpath("//b[text()='Synopsis']/following-sibling::text()[1]").text
    self.update(cover: cover, title: title, description: description)

    manga_info.css('.element .title a').each do |f, index|
      chapter = self.chapters.find_or_create_by(url: f.attr('href'), title: f.text)
      chapter.update(index: index)
    end

  end
end


# t.string   "title"
# t.string   "description"
# t.string   "cover"
# t.string   "thumbnail"

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: [:show, :edit, :update, :destroy]

  # GET /mangas
  # GET /mangas.json
  def index
    @mangas = Manga.all
  end

  # GET /mangas/1
  # GET /mangas/1.json
  def show
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas
  # POST /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: 'Manga was successfully created.' }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1
  # PATCH/PUT /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: 'Manga was successfully updated.' }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1
  # DELETE /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: 'Manga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manga_params
      params.require(:manga).permit(:title, :description, :source)
    end
end

app/helpers/manga/chapters_helper.rb
module Manga::ChaptersHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_form.html.slim
= form_for @manga do |f|
  - if @manga.errors.any?
    #error_explanation
      h2 = "#{pluralize(@manga.errors.count, "error")} prohibited this manga from being saved:"
      ul
        - @manga.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :source
    = f.text_field :source
  .actions = f.submit

app/views/mangas/edit.html.slim
h1 Editing manga

== render 'form'

= link_to 'Show', @manga
'|
= link_to 'Back', mangas_path

app/views/mangas/index.html.slim
/ h1 Listing mangas

/ table.table
/   thead
/     tr
/       th Title
/       th Description
/       th Source
/       th
/       th
/       th

/   tbody
/     - @mangas.each do |manga|
/       tr
/         td = manga.title
/         td = manga.description
/         td = manga.source
/         td = link_to 'Show', manga
/         td = link_to 'Edit', edit_manga_path(manga)
/         td = link_to 'Destroy', manga, data: { confirm: 'Are you sure?' }, method: :delete

/ br

/ = link_to 'New Manga', new_manga_path
.row
- Manga.all.each do |manga|
  .col-md-3
    a href=manga_path(manga)
      .panel.panel-default
        .panel-body = image_tag manga.cover, style:"width:100%"
        .panel-footer = manga.title

app/views/mangas/new.html.slim
h1 New manga

== render 'form'

= link_to 'Back', mangas_path

app/views/mangas/show.html.slim
p#notice = notice

p
  strong Title:
  = @manga.title
p
  strong Description:
  = @manga.description
p
  strong Source:
  = @manga.source

table.table
  thead
    th Chapter
    th Date
  tbody
    - @manga.chapters.each do |chapter|
      tr
        td = link_to chapter.title, manga_chapter_path(manga_id: @manga.id, id: chapter.id)
        td = chapter.created_at.strftime("%d-%m-%Y")

/ = link_to 'Edit', edit_manga_path(@manga)
/ '|
/ = link_to 'Back', mangas_path