config/routes.rb
Rails.application.routes.draw do
  resources :mangas do
    resources :chapters
  end
  resources :teams
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :products do
    collection do
      post :import
      post :remove_all_records
      get :get_price
      get :csv
    end
  end
  resources :departments
  resources :employees
  resources :comments
  root 'pages#home'
  get 'test' => 'pages#test'

  resources :records
  # root 'records#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(author: params[:author], text: params[:text])
    @comment = Comment.new(comment_params)
    if @comment.save
      render json: @comment
    else
      render json: @comment.errors
    end
    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      # format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      # params.fetch(:comment, {})
      params.require(:comment).permit(:author, :text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.slim
- data = [{id: 1, author: "Pete Hunt", text: "This is one comment"},
  {id: 2, author: "Jordan Walke", text: "This is *another* comment"}]
= react_component 'CommentBox', url: "/comments", pollInterval: 2000
br


/ p#notice = notice
/ 
/ h1 Comments
/ 
/ table.table
/   thead
/     tr
/       th colspan="5"
/   tbody
/     -@comments.each do |comment|
/       tr
/         td = link_to 'Show', comment
/         td = comment.author
/         td = comment.text
/         td = link_to 'Edit', edit_comment_path(comment)
/         td = link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
/ br
/ 
/ = link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New Comment

= simple_form_for @comment do |t|
  = t.input :author
  = t.input :text
  = t.button :submit
= link_to 'Back', comments_path

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>