config/routes.rb
Rails.application.routes.draw do
  resources :mangas do
    resources :chapters
  end
  resources :teams
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :products do
    collection do
      post :import
      post :remove_all_records
      get :get_price
      get :csv
    end
  end
  resources :departments
  resources :employees
  resources :comments
  root 'pages#home'
  get 'test' => 'pages#test'

  resources :records
  # root 'records#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  def self.to_csv products
    attributes = %w{code name price}
    (CSV.generate(headers: true) do |csv|
      csv << attributes
      products.each do |p|
        csv << attributes.map{ |attr| p.send(attr) }
      end
    end).encode("Windows-1252", :undef => :replace, :replace => '')
  end


  def self.import(file)
    xlsx = open_spreadsheet(file)
    (2..xlsx.last_row).each do |i|
      data  = xlsx.row(i)
      Product.create(code: data[1])
    end
  end

  def self.open_spreadsheet(file)
    Roo::Spreadsheet.open(file.path)
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def csv
    send_data Product.to_csv(Product.all), filename: "students.csv"
  end

  def get_price
    UpdatePrice.perform_async()
    redirect_to products_path, notice: "Product price is being updated, please check later"
  end

  def import
    Product.destroy_all
    Product.import(params[:file])
    redirect_to products_path, notice: "Product imported"
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv { send_data Product.to_csv(@products) }
      format.xls
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_all_records
    Product.destroy_all
    flash[:info] = "All records had been deleted"
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :name %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.slim
p#notice= notice

= link_to "Delete All", remove_all_records_products_path, method: :post, class:'btn btn-danger pull-right'
= link_to "Update Price", get_price_products_path, class: 'btn btn-success pull-right'
= link_to "CSV", products_path(format: "csv"), class: 'btn btn-info pull-right'
= form_tag import_products_path, multipart: true, html:{class:'pull-right'} do
  = submit_tag "Import", class:'btn btn-primary', disabled:'disabled', id:'submit_file'
  = file_field_tag :file, style:''



h1 Products
table.table.table-condensed.table-striped
  thead
    tr.info
      th Code
      th Name
      th Price
  tbody
    - @products.each do |product|
      tr
        td= product.code
        td= product.name
        td= product.price
        


javascript:
  $('input#file').on('change', function(){
    $('#submit_file').prop("disabled", false);
  });

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Code</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>