config/routes.rb
Rails.application.routes.draw do
  resources :mangas do
    resources :chapters
  end
  resources :teams
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :products do
    collection do
      post :import
      post :remove_all_records
      get :get_price
      get :csv
    end
  end
  resources :departments
  resources :employees
  resources :comments
  root 'pages#home'
  get 'test' => 'pages#test'

  resources :records
  # root 'records#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :manga
  has_many :images

  def update_images

    chapter_info = Nokogiri::HTML(open(url))
    max_page = chapter_info.css('.tbtitle.dropdown_parent.dropdown_right.mmh .text').text().delete(" ⤵").to_i

    for number in 1..max_page do
      image_link = url + "page/" + number.to_s
      image_url = Nokogiri::HTML(open(image_link)).css('.open').first.attr('src')
      self.images.create(index: number, url: image_url)
    end

  end
end

app/models/manga.rb
class Manga < ApplicationRecord
  has_many :chapters

  def update_info
    manga_info = Nokogiri::HTML(open(url))
    cover = manga_info.css('.thumbnail img').first.attr('src')
    title = manga_info.xpath("//div[@class='large comic']/h1/text()").to_s.squish
    description = manga_info.xpath("//b[text()='Synopsis']/following-sibling::text()[1]").text
    self.update(cover: cover, title: title, description: description)

    manga_info.css('.element .title a').each do |f, index|
      chapter = self.chapters.find_or_create_by(url: f.attr('href'), title: f.text)
      chapter.update(index: index)
    end

  end
end


# t.string   "title"
# t.string   "description"
# t.string   "cover"
# t.string   "thumbnail"

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def show
    @chapter = Chapter.find(params[:id])
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :set_manga, only: [:show, :edit, :update, :destroy]

  # GET /mangas
  # GET /mangas.json
  def index
    @mangas = Manga.all
  end

  # GET /mangas/1
  # GET /mangas/1.json
  def show
  end

  # GET /mangas/new
  def new
    @manga = Manga.new
  end

  # GET /mangas/1/edit
  def edit
  end

  # POST /mangas
  # POST /mangas.json
  def create
    @manga = Manga.new(manga_params)

    respond_to do |format|
      if @manga.save
        format.html { redirect_to @manga, notice: 'Manga was successfully created.' }
        format.json { render :show, status: :created, location: @manga }
      else
        format.html { render :new }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mangas/1
  # PATCH/PUT /mangas/1.json
  def update
    respond_to do |format|
      if @manga.update(manga_params)
        format.html { redirect_to @manga, notice: 'Manga was successfully updated.' }
        format.json { render :show, status: :ok, location: @manga }
      else
        format.html { render :edit }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1
  # DELETE /mangas/1.json
  def destroy
    @manga.destroy
    respond_to do |format|
      format.html { redirect_to mangas_url, notice: 'Manga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga
      @manga = Manga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manga_params
      params.require(:manga).permit(:title, :description, :source)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/manga/chapters_helper.rb
module Manga::ChaptersHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/chapters/_form.html.slim
= form_for @manga_chapter do |f|
  - if @manga_chapter.errors.any?
    #error_explanation
      h2 = "#{pluralize(@manga_chapter.errors.count, "error")} prohibited this manga_chapter from being saved:"
      ul
        - @manga_chapter.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :chapter_name
    = f.text_field :chapter_name
  .field
    = f.label :chapter_index
    = f.number_field :chapter_index
  .field
    = f.label :manga_id
    = f.number_field :manga_id
  .field
    = f.label :uploaded_date
    = f.date_select :uploaded_date
  .actions = f.submit

app/views/mangas/chapters/edit.html.slim
h1 Editing manga_chapter

== render 'form'

= link_to 'Show', @manga_chapter
'|
= link_to 'Back', manga_chapters_path

app/views/mangas/chapters/index.html.slim
h1 Listing manga_chapters

table
  thead
    tr
      th Chapter name
      th Chapter index
      th Manga
      th Uploaded date
      th
      th
      th

  tbody
    - @manga_chapters.each do |manga_chapter|
      tr
        td = manga_chapter.chapter_name
        td = manga_chapter.chapter_index
        td = manga_chapter.manga_id
        td = manga_chapter.uploaded_date
        td = link_to 'Show', manga_chapter
        td = link_to 'Edit', edit_manga_chapter_path(manga_chapter)
        td = link_to 'Destroy', manga_chapter, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Chapter', new_manga_chapter_path

app/views/mangas/chapters/new.html.slim
h1 New manga_chapter

== render 'form'

= link_to 'Back', manga_chapters_path

app/views/mangas/chapters/show.html.slim
p#notice = notice

p
  strong Chapter name:
  = @manga_chapter.chapter_name
p
  strong Chapter index:
  = @manga_chapter.chapter_index
p
  strong Manga:
  = @manga_chapter.manga_id
p
  strong Uploaded date:
  = @manga_chapter.uploaded_date

= link_to 'Edit', edit_manga_chapter_path(@manga_chapter)
'|
= link_to 'Back', manga_chapters_path